In [2]:
import numpy as np
import pandas as pd

In [3]:
# Generate pixel coordinates
def random_integers(n, interval, seed):
    seed_sequence = np.random.SeedSequence(seed)
    rng = np.random.default_rng(seed)
    integers = rng.integers(low=min(interval), high=max(interval), size=n)
    return integers

seed_x, seed_y = 111, 222
pixel_range = [25, 2048]
n_locations = 50

df = pd.DataFrame({'X': random_integers(n=n_locations, interval=pixel_range, seed=seed_x),
                   'Y': random_integers(n=n_locations, interval=pixel_range, seed=seed_y)})

# Let's calibrate the pixel values
# We calibrate the microscope with a micrometer scale
# The calibration is 700 pixels / 100 um = 7 pixels/um

factor = 7

df = df.assign(X1=df['X']/factor,  
               Y1=df['Y']/factor)

display(df)

       X     Y          X1          Y1
0    984   850  140.571429  121.428571
1    335   788   47.857143  112.571429
2   1488   723  212.571429  103.285714
3    367  1448   52.428571  206.857143
4   1467    56  209.571429    8.000000
5   1048  1486  149.714286  212.285714
6    761  1702  108.714286  243.142857
7   1356  1777  193.714286  253.857143
8   1753  1036  250.428571  148.000000
9   1577  1836  225.285714  262.285714
10  1478   501  211.142857   71.571429
11   245   186   35.000000   26.571429
12   312   582   44.571429   83.142857
13  1638  1148  234.000000  164.000000
14   962    69  137.428571    9.857143
15  1984  1101  283.428571  157.285714
16   289  1334   41.285714  190.571429
17   524  1148   74.857143  164.000000
18  1026  1098  146.571429  156.857143
19   424   993   60.571429  141.857143
20   937  1258  133.857143  179.714286
21   709   813  101.285714  116.142857
22   193  1706   27.571429  243.714286
23  1472   200  210.285714   28.571429
24  1618  1500  231.142857  214.285714
25   184   769   26.285714  109.857143
26  1849   604  264.142857   86.285714
27   866   215  123.714286   30.714286
28  1492  1280  213.142857  182.857143
29   829   983  118.428571  140.428571
30  1290   877  184.285714  125.285714
31  1924  1239  274.857143  177.000000
32   841   112  120.142857   16.000000
33   642  1513   91.714286  216.142857
34  1180   450  168.571429   64.285714
35  1256   528  179.428571   75.428571
36   209   364   29.857143   52.000000
37  1522  1419  217.428571  202.714286
38   991   268  141.571429   38.285714
39   182  1342   26.000000  191.714286
40   887  1747  126.714286  249.571429
41  1754  1523  250.571429  217.571429
42   133   405   19.000000   57.857143
43  1074  1000  153.428571  142.857143
44   390   372   55.714286   53.142857
45  1779  1508  254.142857  215.428571
46   758  1949  108.285714  278.428571
47   950   656  135.714286   93.714286
48  1064  2009  152.000000  287.000000
49  1879   529  268.428571   75.571429